### ISSUE TITLE
updating parent reactive props in child component doesn't work

### ISSUE THREAD

**Issue by Leonidaz** [trueadm/ripple#12]
Ran into these 2 "issues":

1. Updating reactive `props.$count` in the child component doesn't update the parent reactive variable.  Is this by design, not supported yet or bug?
    ```jsx
    component Button(props) {
      <button onClick={() => { props.$count++; } }>{"child: "}{props.$count}</button>
    }
    
    export component App() {
      <div>
        let $count = 0;
    
        <span>{"parent: "} {$count}</span>
        <span>{" "}</span>
        <Button {$count} />
      </div>
    }
    ```

    but passing in an object works as expected:
    ```jsx
    component Button({obj}) {
      <button onClick={() => { obj.$count++; } }>{"child: "}{obj.$count}</button>
    }
    
    export component App() {
      <div>
        let obj = { $count: 0 };
    
        <span>{"parent: "} {obj.$count}</span>
        <span>{" "}</span>
        <Button {obj} />
      </div>
    }
    ```

2. updating desctructured prop causes an error in the `onClick` handler as `_props` is `undefined`

    component code:
    ```jsx
    component Button({$count}) {
      <button onClick={() => { $count++; } }>{"child: "}{$count}</button>
    }
    
    export component App() {
      <div>
        let $count = 0;
    
        <span>{"parent: "} {$count}</span>
        <span>{" "}</span>
        <Button {$count} />
      </div>
    }
    ```
    
    the `onClick` is compiled into but `__props` is not passed to the handler:
    ```js
    var on_click = (__block) => {
    	$.get_property(__props, '$count')++;
    };
    ```
    
    and called from:
    ```js
    button_1.__click = [on_click, __block];
    ```

**Comment by trueadm** [comment]
Should be fixed now

**Comment by leonidaz** [comment]
maybe you meant to comment on the #13, as both of these cases are still not working.

**Comment by trueadm** [comment]
> Updating reactive props.$count in the child component doesn't update the parent reactive variable. Is this by design, not supported yet or bug? (svelte uses bind: and $bindsble() to enable the reverse updates). If you looked at the compiled output, we're passing in a `props` object that has a computed property so that it can capture reactivity. Writes wouldn't go bi-directional and would be tricky with cases like:

```tsx
<Button $count={foo ? $count: $bar} />
```

This is by design, props are their own reactive object and don't pass writes of state through – so you can optimistic state locally in a component. We'd have to switch to getters/setters objects to make it flow through instead and invent some kind of `bind:` syntax.

I'm actually not a big fan of `bind:` and the amount of bugs I've had to debug in Svelte 5 related to their abuse as when it comes to tracking the source of the issue it gets complicated. Objects that you pass through will retain their reactivity, and is a way of getting around this if people want.

> updating desctructured prop causes an error in the onClick handler as _props is undefined

The second example should fail, you can't write to a destructured prop, it won't do anything and isn't allowed. You should get the compiler error:

> Cannot update component prop property, component props are not writable

Maybe another bug was fixed that ensured this now fails correctly.

**Comment by trueadm** [comment]
Come to think of it, I think we can probably do better with the second case, let me try and make it work like the first case.

**Comment by leonidaz** [comment]
Ok, gotcha, so it will be a one way flow unless there is an object reference to the parent.  It's safer to pass in callbacks from parent to client anyway.

tbh, the simpler the better, Svelte did have a ton of constant bugs in this area and it was kind of frustrating working with it at times because of these issues.

_SIDE NOTE: We should probably emphasize this in the docs / readme at some point as ripple does bear similarity to svelte and it seemed like a big chunk of the svelte community follows your work. (e.g. `Data Flow` section with some examples).  You already added some tests and we can use the same examples.  No rush obviously, just a TODO.  My only hesitation to do it now is just to wait until the framework stabilizes, or in case something changes._

I saw that you just merged a way to have disconnected states between parent and child, sounds good! It's just like regular JS behavior: passing in all primitives by value and objects by reference with `props` being a local construct.

One thing that would definitely be very helpful though is to have a way for child components to expose some methods for the parent to call, to control its behavior as needed.  I know you said that you didn't like Svelte instances (although they were file based) but seemed like you have some ideas of how to better accomplish this.

**Comment by trueadm** [comment]
> SIDE NOTE: We should probably emphasize this in the docs / readme at some point as ripple does bear similarity to svelte and it seemed like a big chunk of the svelte community follows your work. (e.g. Data Flow section with some examples). You already added some tests and we can use the same examples. No rush obviously, just a TODO. My only hesitation to do it now is just to wait until the framework stabilizes, or in case something changes.

If you have any suggestions to improve the README, please go ahead and great a PR :)

As for the communication of parent -> child and child -> parent, that's the big next API goal. I first want to implement type safety context, which will largely work like React, and then deal with the reverse case so components can expose themselves to the parent components. The issue with Svelte was that the `bind:` system was only 1 level deep, and that made working with indirection components complicated, especially when dealing with large enterprise apps. I had already tackled this with scopes in React, but it was never released (it's still marked as experimental in the codebase, yet is a major underpinning for a11y for all of Facebook and Instagram lol)

**Comment by WebEferen** [comment]
Can we close this ticket (to get rid of week old issues from the board?) @trueadm
