### ISSUE TITLE
vscode angry squiggles - block and $ issues

### ISSUE THREAD

**Issue by leonidaz** [trueadm/ripple#18]
1. the first error is `Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.ts(2581)`

2. and the second: `Cannot find name '__block'.ts(2304)`

<img width="628" height="260" alt="Image" src="https://github.com/user-attachments/assets/851a513c-7509-4843-8682-5d5cee8940d5" />

code: 

```jsx
export component App() {
  let obj = { $count: 0, $value: 0 };
  let $value = 0;
}

```

_NOTE: Both can happen even within blocks, e.g. `<div>...</div>`_

**Comment by WebEferen** [comment]
Should be fixed in this PR: #165

**Comment by leonidaz** [comment]
@WebEferen as per Jake, there are still a couple of issues remain, as per #165 comments after the merge.  If you have time would you mind looking into them?

**Comment by JakeIsMeh** [comment]
syntax and LSP has gone through a lot of churn, outdated.
