### ISSUE TITLE
[Bug]: for loop is not rendering $children

### ISSUE THREAD

**Issue by chandani-rathi** [trueadm/ripple#185]
### Issue Category

Compilation Bug

### Bug Description

Getting compilation error when using for loop and component $children

`Error: Uncaught TypeError: Cannot read properties of null (reading 'cloneNode')`

Minimal reproduction:

```jsx
import { RippleArray } from "ripple"

component Item({ $children }){
  <li>
    <$children />
  </li>
}

component ListView({ title, items }) {
  <h2>{title}</h2>
  <ul>
    for (const item of items) {
      <Item>{item.text}</Item>
    }
  </ul>
}

export default component App() {
  const items = new RippleArray({text: 1}, {text: 2}, {text: 3})
  <div class="container">
    <ListView title={"Numbers"} items={items} />
  </div>
}
```

### Reproduction Steps

link to reproduction: https://ripple.livecodes.pages.dev/?x=id/ypvhasssim8

### Environment

```markdown
- latest ripple version
```

### Additional Context

changing the for-loop variable to $item, works correctly.

### Checklist

- [x] I've searched for existing issues
- [ ] I'm willing to help implement a fix

**Comment by WebEferen** [comment]
Seems like it is working fine when you'd mark the item from the for loop as reactive.

Try this snippet:
```
import { RippleArray } from "ripple"

component Item({ $children }){
  <li>
    <$children />
  </li>
}

component ListView({ title, items }) {
  <h2>{title}</h2>
  <ul>
    for (const $item of items) {
      <Item>{$item.text}</Item>
    }
  </ul>
}

export default component App() {
  const items = new RippleArray({ text: 1}, { text: 2 }, { text: 3})
  <div class="container">
    <ListView title={"Numbers"} items={items} />
  </div>
}
```
Question for @trueadm - is this intended for this particular case? If the above snipped is proper, then can we create proper error message to instruct users that they cannot bind tracked (reactive) properties into normal untracked ones (even when using for loop). If this is correct way of thinking then I'd update error message to properly guide user that they are trying to use tracked/reactive properties as normal ones.

**Comment by trueadm** [comment]
This was a bug that has since been fixed in the latest version. See https://github.com/trueadm/ripple/commit/fd0a96ec38e83c1152a62f18a1454cd06ca4fcd8

It would be good if someone could create a regression test for this in the for vitiest test module :) I haven't got time atm

@WebEferen this should work as static text, which now does accordingly

**Comment by WebEferen** [comment]
Thanks, I will add such tests. Closing the issue.

**Comment by chandani-rathi** [comment]
@WebEferen : 

I am still not understanding which way correct way to use for loop.

Please see below example when I used html tag directly in loop to rending text it works but only when custom component is created and passed as children prop it is not working. Verified in latest version.

```
import { RippleArray } from "ripple"

component Item({ $children }){
  <li>
    <$children />
  </li>
}

component ListViewWithItem({ title, items }) {
  <h2>{title}</h2>
  <ul>
    for (const item of items) {
      <Item>{item.text}</Item>
    }
  </ul>
}


component ListViewWithoutItem({ title, items }) {
  <h2>{title}</h2>
  <ul>
    for (const item of items) {
      <li>{item.text}</li>
    }
  </ul>
}

export default component App() {
  const items = new RippleArray({ text: 1}, { text: 2 }, { text: 3})
  <div class="container">
    <ListViewWithItem title={"Numbers with Item"} items={items} />
    <hr />
    <ListViewWithoutItem title={"Numbers without Item"} items={items} />
  </div>
}
```
Rendered HTML

<img width="420" height="452" alt="Image" src="https://github.com/user-attachments/assets/74553fce-1c66-4c2d-8517-2d08ce224aa2" />

**Comment by chandani-rathi** [comment]
this is fixed in latest version.

Belew is updated code with TrackedArray.
```
import { TrackedArray } from "ripple"

component Item({ children }){
  <li>
    <children />
  </li>
}

component ListViewWithItem({ title, items }) {
  <h2>{title}</h2>
  <ul>
    for (const item of items) {
      <Item>{item.text}</Item>
    }
  </ul>
}


component ListViewWithoutItem({ title, items }) {
  <h2>{title}</h2>
  <ul>
    for (const item of items) {
      <li>{item.text}</li>
    }
  </ul>
}

export default component App() {
  const items = new TrackedArray({ text: 1}, { text: 2 }, { text: 3})
  <div class="container">
    <ListViewWithItem title={"Numbers with Item"} items={items} />
    <hr />
    <ListViewWithoutItem title={"Numbers without Item"} items={items} />
  </div>
}
```
