### ISSUE TITLE
TSTypelist

### ISSUE THREAD

**Issue by ScorpioneOrzion** [trueadm/ripple#382]
type t0 = undefined;
type t1 = number;
type t2 = string;
type t3 = boolean;
type t4 = null;
type t5 = symbol;
type t6 = bigint;
type t7 = any;
type t8 = unknown;
type t9 = never;
type t10 = void;
type t11 = { a: number; b: string };
type t12 = keyof t11;
const T0: t17 = { x: 1 };
type t13 = typeof T0;
type t14 = Partial\<t11>;
type t15 = Required\<t14>;
type t16 = Readonly\<t15>;
type t17 = Record<string, number>;
type t18 = Pick<t11, 'a'>;
type t19 = Omit<t11, 'b'>;
type t20 = ReturnType<() => string>;
type t21 = Parameters<(x: number, y: string) => void>;

**Comment by ScorpioneOrzion** [comment]
type t22 = Function;
type t23 = Array\<number>;
type t24 = [string, number]; // Tuple
type t25 = { [key: string]: any }; // Index signature
type t26 = () => void; // Function type
type t27 = new () => object; // Constructor type
type t28 = Exclude<'a' | 'b', 'b'>; // "a"
type t29 = Extract<'a' | 'b', 'b'>; // "b"
type t30 = NonNullable<string | null>; // string
type t31 = InstanceType\<typeof SomeClass>;
type t32 = ThisType<{ x: number }>; // contextual `this`
type t33\<T> = T extends string ? 'yes' : 'no';
type t34\<T> = { [K in keyof T]: T[K] }; // mapped type
type t35\<T> = { [K in keyof T as `get${Capitalize\<string & K>}`]: () => T[K] }; // remapped keys
type t36 = typeof globalThis;
type t37 = Awaited\<Promise\<string>>;
type t38 = ReadonlyArray\<number>;
type t39 = TemplateStringsArray;
type t40 = unknown extends any ? true : false; // conditional logic
type t41 = ReturnType\<typeof Math.max>;
type t42 = Parameters\<typeof setTimeout>;
type t43 = ConstructorParameters\<typeof Error>;
type t44 = Uppercase\<'hello'>; // "HELLO"
type t45 = Lowercase\<'HELLO'>; // "hello"
type t46 = Capitalize\<'hello'>; // "Hello"
type t47 = Uncapitalize\<'Hello'>; // "hello"

**Comment by trueadm** [comment]
Should be fixed now!

**Comment by ScorpioneOrzion** [comment]
t24, t25, t27, t33, t34, t35 and t41 still fail, rest does work
Their types are TSTupleType, TSIndexSignature, TSConstructorType, TSConditionalType, TSMappedType and TSQualifiedName

**Comment by trueadm** [comment]
Ah my bad, re-opening

**Comment by ScorpioneOrzion** [comment]
at least most of them work

**Comment by ScorpioneOrzion** [comment]
Only things that go wrong now are, t21, t27 and t41
with
prettier-plugin-ripple 0.2.105
vite 7.1.9
vite-plugin-ripple 0.2.105

t21: strips the parameters, from an inline function `Parameters<(x: number, y: string) => void>;` into `Parameters<() => void>;`
t27: `object` isn't know (but should be simple)
t41: turns `ReturnType<typeof Math.max>;` into `ReturnType<typeof Math,.,max>;`

**Comment by leonidaz** [comment]
ok, just pushed a fixed to main, will publish a new version later.

all types referenced in this issue are now supported.

closing.
