### ISSUE TITLE
[Bug]: combination of variables with the same name breaks type information / LSP

### ISSUE THREAD

**Issue by kuechlerm** [trueadm/ripple#397]
### Issue Category

Compilation Bug

### Bug Description

Please read the comments in the code below:

```ts
import { track } from 'ripple';

const create_state = () => {
	let count = track(1); // this line shows information on hover as expected
	return {
		// this + line 15 breaks the LSP - commenting out this line helps
		count, // hovering this line shows information but without colors
	};
};

export default component Test() {
	let a = track('A'); // hovering this shows nothing

	// even commenting out this line doesn't help!
	let count = track(0); // line 15 / only the word count shows something on hover, but not track

	<div>{'Test'}</div>
}
```

### Reproduction Steps

See code above

### Environment

```markdown
- VS Code with current Ripple extension
dependencies:
+ ripple 0.2.103

devDependencies:
+ prettier-plugin-ripple 0.2.103
+ vite 7.1.9
+ vite-plugin-ripple 0.2.103
```

### Checklist

- [x] I've searched for existing issues
- [ ] I'm willing to help implement a fix

**Comment by niharsoni16** [comment]
Hi @kuechlerm,

Could you please clarify a bit? From your observation, are you specifically referring to certain file types where this occurs, like .ripple or .vue? Or are you speaking from a development perspective, where while coding and hovering, the context of count or track isn’t showing as expected?

Also, I wanted to confirm — is the snippet you shared just an example, or is this something we need to consider and handle consistently across other files as well?

Thanks!

**Comment by kuechlerm** [comment]
Hi @niharsoni16 ,
Sorry, I was a bit brief, I guess.
When I have this code in a ripple file in vs Code the on mouse hover LSP infos act the way I describe in the comments. 
In short: return count ... and let count ... break the LSP.

**Comment by trueadm** [comment]
We pushed a change to the extension today, hopefully this resolves this issue.

**Comment by kuechlerm** [comment]
Just rechecked with the lastest Ripple for VS Code 0.0.21.
The problem is still the same.

**Comment by trueadm** [comment]
This is so strange, it seems to work fine for me?

<img width="784" height="352" alt="Image" src="https://github.com/user-attachments/assets/e5e36c18-0523-446c-b199-388016dae70a" />
<img width="941" height="357" alt="Image" src="https://github.com/user-attachments/assets/102efa47-0190-4c97-8e65-f8556d8fd373" />

**Comment by kuechlerm** [comment]
Thats funny, if I change the line 11 as you did to:
```ts
export component App() {
```
then everything in line 15 works. But not in line 12!
And in my example:
```ts
export default component Test() {
```
track(0) in line 15 does not work aswell.

**Comment by trueadm** [comment]
I've figured it out:

```
{ count }
```

It technically is two nodes `{ count: count }` at an AST level, this now makes sense as to why it broke. Fix will be incoming

**Comment by trueadm** [comment]
Okay I pushed an update to Ripple, please update your packages

**Comment by kuechlerm** [comment]
Great! It works now. Thank you.
